In [100]:
import pandas as pd
df=pd.read_csv("311.csv")
df

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,64446107,03/24/2025 11:33:07 PM,03/25/2025 12:45:11 AM,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,11210,1155 EAST 35 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.625991,-73.941889,"(40.625990681603746, -73.94188882855283)"
1,64453126,03/24/2025 11:29:00 PM,03/25/2025 03:53:00 PM,DEP,Department of Environmental Protection,Noise,Noise: Jack Hammering (NC2),NaN,10016,11 EAST 31 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.746206,-73.985142,"(40.74620615004179, -73.98514193912169)"
2,64454142,03/24/2025 11:25:22 PM,NaN,DOE,Department of Education,School Maintenance,Rodents/Mice,School,10025,163 WEST 97 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.794442,-73.969139,"(40.794441772310265, -73.96913914902804)"
3,64448747,03/24/2025 11:08:24 PM,03/24/2025 11:30:36 PM,NYPD,New York City Police Department,Noise - Residential,Loud Talking,Residential Building/House,10025,330 WEST 95 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.795083,-73.974910,"(40.79508269493676, -73.97491019376804)"
4,64451190,03/24/2025 11:07:50 PM,03/25/2025 12:16:18 AM,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,10027,200 WEST 131 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.812812,-73.945739,"(40.81281181632886, -73.94573926927536)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,64441334,03/24/2025 01:02:55 AM,03/24/2025 02:02:11 AM,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,11210,2021 FARRAGUT ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.635330,-73.957899,"(40.63532994216788, -73.9578994454981)"
231,64450667,03/24/2025 12:50:00 AM,03/24/2025 01:41:00 PM,DEP,Department of Environmental Protection,Lead,Lead Kit Request (Residential) (L10),NaN,10016,425 PARK AVENUE SOUTH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.744081,-73.983515,"(40.744081492435235, -73.98351482688908)"
232,64437785,03/24/2025 12:17:47 AM,03/24/2025 01:40:49 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11210,1416 NEW YORK AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.638144,-73.945316,"(40.638143542877394, -73.94531561201252)"
233,64439380,03/24/2025 12:15:41 AM,03/24/2025 03:03:22 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10016,30 EAST 30 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.745125,-73.984532,"(40.74512463850905, -73.98453227710138)"
234,64439049,03/24/2025 12:01:56 AM,03/24/2025 12:47:13 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10016,30 EAST 30 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.745125,-73.984532,"(40.74512463850905, -73.98453227710138)"

In [101]:
df.columns

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip',
       'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
       'Intersection Street 1', 'Intersection Street 2', 'Address Type',
       'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
       'Resolution Description', 'Resolution Action Updated Date',
       'Community Board', 'BBL', 'Borough', 'X Coordinate (State Plane)',
       'Y Coordinate (State Plane)', 'Open Data Channel Type',
       'Park Facility Name', 'Park Borough', 'Vehicle Type',
       'Taxi Company Borough', 'Taxi Pick Up Location', 'Bridge Highway Name',
       'Bridge Highway Direction', 'Road Ramp', 'Bridge Highway Segment',
       'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [102]:
df=df[["Created Date", "Closed Date", "Complaint Type", "Incident Zip", "Incident Address", 'Latitude', 'Longitude']]
df

,Created Date,Closed Date,Complaint Type,Incident Zip,Incident Address,Latitude,Longitude
0,03/24/2025 11:33:07 PM,03/25/2025 12:45:11 AM,Noise - Residential,11210,1155 EAST 35 STREET,40.625991,-73.941889
1,03/24/2025 11:29:00 PM,03/25/2025 03:53:00 PM,Noise,10016,11 EAST 31 STREET,40.746206,-73.985142
2,03/24/2025 11:25:22 PM,NaN,School Maintenance,10025,163 WEST 97 STREET,40.794442,-73.969139
3,03/24/2025 11:08:24 PM,03/24/2025 11:30:36 PM,Noise - Residential,10025,330 WEST 95 STREET,40.795083,-73.974910
4,03/24/2025 11:07:50 PM,03/25/2025 12:16:18 AM,Noise - Residential,10027,200 WEST 131 STREET,40.812812,-73.945739
...,...,...,...,...,...,...,...
230,03/24/2025 01:02:55 AM,03/24/2025 02:02:11 AM,Noise - Residential,11210,2021 FARRAGUT ROAD,40.635330,-73.957899
231,03/24/2025 12:50:00 AM,03/24/2025 01:41:00 PM,Lead,10016,425 PARK AVENUE SOUTH,40.744081,-73.983515
232,03/24/2025 12:17:47 AM,03/24/2025 01:40:49 AM,Noise - Residential,11210,1416 NEW YORK AVENUE,40.638144,-73.945316
233,03/24/2025 12:15:41 AM,03/24/2025 03:03:22 AM,Noise - Street/Sidewalk,10016,30 EAST 30 STREET,40.745125,-73.984532
234,03/24/2025 12:01:56 AM,03/24/2025 12:47:13 AM,Noise - Street/Sidewalk,10016,30 EAST 30 STREET,40.745125,-73.984532

In [103]:
df["Created Date"] = pd.to_datetime(df["Created Date"], errors='coerce')
df

/var/folders/2h/mxr2292918v68144kbqd531r0000gn/T/ipykernel_3605/1323214052.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Created Date"] = pd.to_datetime(df["Created Date"], errors='coerce')
/var/folders/2h/mxr2292918v68144kbqd531r0000gn/T/ipykernel_3605/1323214052.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Created Date"] = pd.to_datetime(df["Created Date"], errors='coerce')

,Created Date,Closed Date,Complaint Type,Incident Zip,Incident Address,Latitude,Longitude
0,2025-03-24 23:33:07,03/25/2025 12:45:11 AM,Noise - Residential,11210,1155 EAST 35 STREET,40.625991,-73.941889
1,2025-03-24 23:29:00,03/25/2025 03:53:00 PM,Noise,10016,11 EAST 31 STREET,40.746206,-73.985142
2,2025-03-24 23:25:22,NaN,School Maintenance,10025,163 WEST 97 STREET,40.794442,-73.969139
3,2025-03-24 23:08:24,03/24/2025 11:30:36 PM,Noise - Residential,10025,330 WEST 95 STREET,40.795083,-73.974910
4,2025-03-24 23:07:50,03/25/2025 12:16:18 AM,Noise - Residential,10027,200 WEST 131 STREET,40.812812,-73.945739
...,...,...,...,...,...,...,...
230,2025-03-24 01:02:55,03/24/2025 02:02:11 AM,Noise - Residential,11210,2021 FARRAGUT ROAD,40.635330,-73.957899
231,2025-03-24 00:50:00,03/24/2025 01:41:00 PM,Lead,10016,425 PARK AVENUE SOUTH,40.744081,-73.983515
232,2025-03-24 00:17:47,03/24/2025 01:40:49 AM,Noise - Residential,11210,1416 NEW YORK AVENUE,40.638144,-73.945316
233,2025-03-24 00:15:41,03/24/2025 03:03:22 AM,Noise - Street/Sidewalk,10016,30 EAST 30 STREET,40.745125,-73.984532
234,2025-03-24 00:01:56,03/24/2025 12:47:13 AM,Noise - Street/Sidewalk,10016,30 EAST 30 STREET,40.745125,-73.984532

In [104]:
df["hour"] = df["Created Date"].dt.hour
df

/var/folders/2h/mxr2292918v68144kbqd531r0000gn/T/ipykernel_3605/1926599790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["hour"] = df["Created Date"].dt.hour

,Created Date,Closed Date,Complaint Type,Incident Zip,Incident Address,Latitude,Longitude,hour
0,2025-03-24 23:33:07,03/25/2025 12:45:11 AM,Noise - Residential,11210,1155 EAST 35 STREET,40.625991,-73.941889,23
1,2025-03-24 23:29:00,03/25/2025 03:53:00 PM,Noise,10016,11 EAST 31 STREET,40.746206,-73.985142,23
2,2025-03-24 23:25:22,NaN,School Maintenance,10025,163 WEST 97 STREET,40.794442,-73.969139,23
3,2025-03-24 23:08:24,03/24/2025 11:30:36 PM,Noise - Residential,10025,330 WEST 95 STREET,40.795083,-73.974910,23
4,2025-03-24 23:07:50,03/25/2025 12:16:18 AM,Noise - Residential,10027,200 WEST 131 STREET,40.812812,-73.945739,23
...,...,...,...,...,...,...,...,...
230,2025-03-24 01:02:55,03/24/2025 02:02:11 AM,Noise - Residential,11210,2021 FARRAGUT ROAD,40.635330,-73.957899,1
231,2025-03-24 00:50:00,03/24/2025 01:41:00 PM,Lead,10016,425 PARK AVENUE SOUTH,40.744081,-73.983515,0
232,2025-03-24 00:17:47,03/24/2025 01:40:49 AM,Noise - Residential,11210,1416 NEW YORK AVENUE,40.638144,-73.945316,0
233,2025-03-24 00:15:41,03/24/2025 03:03:22 AM,Noise - Street/Sidewalk,10016,30 EAST 30 STREET,40.745125,-73.984532,0
234,2025-03-24 00:01:56,03/24/2025 12:47:13 AM,Noise - Street/Sidewalk,10016,30 EAST 30 STREET,40.745125,-73.984532,0

In [105]:
df["Complaint Type"] = df["Complaint Type"].replace(
    to_replace=r"^Noise.*", value="Noise", regex=True
)

/var/folders/2h/mxr2292918v68144kbqd531r0000gn/T/ipykernel_3605/3247211741.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Complaint Type"] = df["Complaint Type"].replace(

In [106]:
df

,Created Date,Closed Date,Complaint Type,Incident Zip,Incident Address,Latitude,Longitude,hour
0,2025-03-24 23:33:07,03/25/2025 12:45:11 AM,Noise,11210,1155 EAST 35 STREET,40.625991,-73.941889,23
1,2025-03-24 23:29:00,03/25/2025 03:53:00 PM,Noise,10016,11 EAST 31 STREET,40.746206,-73.985142,23
2,2025-03-24 23:25:22,NaN,School Maintenance,10025,163 WEST 97 STREET,40.794442,-73.969139,23
3,2025-03-24 23:08:24,03/24/2025 11:30:36 PM,Noise,10025,330 WEST 95 STREET,40.795083,-73.974910,23
4,2025-03-24 23:07:50,03/25/2025 12:16:18 AM,Noise,10027,200 WEST 131 STREET,40.812812,-73.945739,23
...,...,...,...,...,...,...,...,...
230,2025-03-24 01:02:55,03/24/2025 02:02:11 AM,Noise,11210,2021 FARRAGUT ROAD,40.635330,-73.957899,1
231,2025-03-24 00:50:00,03/24/2025 01:41:00 PM,Lead,10016,425 PARK AVENUE SOUTH,40.744081,-73.983515,0
232,2025-03-24 00:17:47,03/24/2025 01:40:49 AM,Noise,11210,1416 NEW YORK AVENUE,40.638144,-73.945316,0
233,2025-03-24 00:15:41,03/24/2025 03:03:22 AM,Noise,10016,30 EAST 30 STREET,40.745125,-73.984532,0
234,2025-03-24 00:01:56,03/24/2025 12:47:13 AM,Noise,10016,30 EAST 30 STREET,40.745125,-73.984532,0

In [113]:
df["Complaint Type"].unique()

array(['Noise', 'School Maintenance', 'Bike Rack', 'HEAT/HOT WATER',
       'Rodent', 'Animal-Abuse', 'Illegal Parking', 'Blocked Driveway',
       'Lead', 'WATER LEAK', 'ELECTRIC', 'PAINT/PLASTER',
       'FLOORING/STAIRS', 'DOOR/WINDOW', 'Street Condition',
       'Water System', 'UNSANITARY CONDITION',
       'For Hire Vehicle Complaint', 'Sewer', 'Animal in a Park',
       'Dirty Condition', 'Abandoned Vehicle', 'Derelict Vehicles',
       'Encampment', 'Lost Property', 'Food Establishment',
       'Vendor Enforcement', 'Dead/Dying Tree', 'Illegal Dumping',
       'General Construction/Plumbing', 'Air Quality',
       'Sidewalk Condition', 'Scaffold Safety', 'GENERAL',
       'Non-Emergency Police Matter', 'Elevator', 'Consumer Complaint',
       'Missed Collection', 'Overgrown Tree/Branches',
       'Homeless Person Assistance', 'SAFETY', 'PLUMBING',
       'Residential Disposal Complaint', 'Boilers', 'Panhandling'],
      dtype=object)

In [123]:
df["Category"] = "Other"  

df.loc[df["Complaint Type"].str.contains(r"^Noise", case=False, na=False), "Category"] = "Noise"
df.loc[df["Complaint Type"].str.contains(r"HEAT|HOT WATER|Boilers", case=False, na=False), "Category"] = "Heat"
df.loc[df["Complaint Type"].str.contains(r"Illegal Parking|Blocked Driveway|Derelict|Abandoned Vehicle", case=False, na=False), "Category"] = "Parking"
df.loc[df["Complaint Type"].str.contains(r"Dirty|UNSANITARY|Rodent|Sewer|Food|Sidewalk", case=False, na=False), "Category"] = "Sanitation"
df.loc[df["Complaint Type"].str.contains(r"Scaffold|SAFETY|Elevator", case=False, na=False), "Category"] = "Safety"
df.loc[df["Complaint Type"].str.contains("WATER LEAK|Water System|ELECTRIC|PLUMBING", case=False), "Category"] = "Infrastructure"
df.loc[df["Complaint Type"].str.contains("DOOR|WINDOW|PAINT|FLOORING|General Construction", case=False), "Category"] = "Building"
df.loc[df["Complaint Type"].str.contains("For Hire|Street Condition|Vendor Enforcement|Dumping|Bike Rack", case=False), "Category"] = "Mobility"
df.loc[df["Complaint Type"].str.contains("Consumer|GENERAL|Lost Property|School|Missed Collection|Non-Emergency|Residential Disposal", case=False), "Category"] = "Civic"

heatmap_data = df.groupby(["Incident Zip", "Category"]).size().unstack(fill_value=0)
heatmap_data

/var/folders/2h/mxr2292918v68144kbqd531r0000gn/T/ipykernel_3605/1038532072.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Category"] = "Other"

Category,Building,Civic,Heat,Infrastructure,Mobility,Noise,Other,Parking,Safety,Sanitation
Incident Zip,,,,,,,,,,
10016,0,3,4,5,9,14,8,5,0,6
10025,4,4,16,5,3,12,5,4,0,7
10027,4,1,13,2,1,12,1,13,2,2
11210,4,10,4,7,3,10,4,19,3,6

In [122]:
complaints.to_csv("311-complaints.csv")